export const LOADING_PAINTINGS = "LOADING_PAINTINGS";
export const LOADED_PAINTINGS = "LOADED_PAINTINGS";
export const SELECT_ACTIVE_PAINTING = "SELECT_ACTIVE_PAINTING";
export const UPDATE_PAINTING = "UPDATE_PAINTING";
export const SELECT_GALLERY = "SELECT_GALLERY";
export const ERROR = "ERROR";
